"""empty message

Revision ID: 17ef0f7a67dd
Revises: 300f7090fbfb
Create Date: 2014-12-05 17:12:53.694677

"""

# revision identifiers, used by Alembic.
revision = '17ef0f7a67dd'
down_revision = '300f7090fbfb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('topotype_id', sa.Integer(), nullable=False))
    op.drop_column('dataset', 'type')
    op.add_column('topotype', sa.Column('ignore_citations', sa.String(length=120), nullable=True))
    op.add_column('topotype', sa.Column('timestamp_column', sa.String(length=120), nullable=True))
    op.drop_column('topotype', 'ignoreCitation')
    op.drop_column('topotype', 'time_column')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topotype', sa.Column('time_column', sa.VARCHAR(length=120), nullable=True))
    op.add_column('topotype', sa.Column('ignoreCitation', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('topotype', 'timestamp_column')
    op.drop_column('topotype', 'ignore_citations')
    op.add_column('dataset', sa.Column('type', sa.VARCHAR(length=120), nullable=False))
    op.drop_column('dataset', 'topotype_id')
    ### end Alembic commands ###
