"""empty message

Revision ID: 19e0711f93bc
Revises: 319c6602f7d8
Create Date: 2015-05-15 18:12:56.210458

"""

# revision identifiers, used by Alembic.
revision = '19e0711f93bc'
down_revision = '319c6602f7d8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'index_name')
    op.drop_column('dataset', 'index_state')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('index_state', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=150), nullable=False))
    op.add_column('dataset', sa.Column('index_name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=150), nullable=True))
    ### end Alembic commands ###
