"""empty message

Revision ID: 296b2056a300
Revises: 43042192957
Create Date: 2014-12-05 12:22:51.478530

"""

# revision identifiers, used by Alembic.
revision = '296b2056a300'
down_revision = '43042192957'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topotype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('languages', sa.String(length=120), nullable=False),
    sa.Column('time_pattern', sa.String(length=120), nullable=True),
    sa.Column('stopwords', sa.Text(), nullable=True),
    sa.Column('ignoreCitation', sa.String(length=120), nullable=True),
    sa.Column('source_column', sa.String(length=120), nullable=True),
    sa.Column('dest_column', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('topogram_type')
    op.add_column('regexp', sa.Column('citation_patterns_id', sa.Integer(), nullable=True))
    op.add_column('regexp', sa.Column('stop_patterns_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_regexp_citation_patterns_id'), 'regexp', ['citation_patterns_id'], unique=False)
    op.create_index(op.f('ix_regexp_stop_patterns_id'), 'regexp', ['stop_patterns_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_regexp_stop_patterns_id'), table_name='regexp')
    op.drop_index(op.f('ix_regexp_citation_patterns_id'), table_name='regexp')
    op.drop_column('regexp', 'stop_patterns_id')
    op.drop_column('regexp', 'citation_patterns_id')
    op.create_table('topogram_type',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('citation_pattern', sa.VARCHAR(length=120), nullable=True),
    sa.Column('dest_column', sa.VARCHAR(length=120), nullable=True),
    sa.Column('ignoreCitation', sa.VARCHAR(length=120), nullable=True),
    sa.Column('languages', sa.VARCHAR(length=120), nullable=True),
    sa.Column('source_column', sa.VARCHAR(length=120), nullable=True),
    sa.Column('stop_patterns', sa.VARCHAR(length=120), nullable=True),
    sa.Column('stopwords', sa.TEXT(), nullable=True),
    sa.Column('time_pattern', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('topotype')
    ### end Alembic commands ###
