"""empty message

Revision ID: 2c6ae0707e99
Revises: b2dd33a7d99
Create Date: 2015-05-15 20:04:22.054475

"""

# revision identifiers, used by Alembic.
revision = '2c6ae0707e99'
down_revision = 'b2dd33a7d99'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
