"""empty message

Revision ID: 2ec1e81b06f8
Revises: 40cf67f2aa92
Create Date: 2014-12-16 18:20:36.410980

"""

# revision identifiers, used by Alembic.
revision = '2ec1e81b06f8'
down_revision = '40cf67f2aa92'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topogram', sa.Column('citations_limit', sa.Integer(), nullable=True))
    op.add_column('topogram', sa.Column('words_limit', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topogram', 'words_limit')
    op.drop_column('topogram', 'citations_limit')
    ### end Alembic commands ###
