"""empty message

Revision ID: 2f02364e3076
Revises: 568d2d75795c
Create Date: 2014-11-29 11:46:23.733481

"""

# revision identifiers, used by Alembic.
revision = '2f02364e3076'
down_revision = '568d2d75795c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('registered_on', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'registered_on')
    ### end Alembic commands ###
