"""empty message

Revision ID: 2fc2f80eea15
Revises: 500722960d68
Create Date: 2014-11-29 11:56:45.507062

"""

# revision identifiers, used by Alembic.
revision = '2fc2f80eea15'
down_revision = '500722960d68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
