"""Add "additional_columns" to dataset structure

Revision ID: 319c6602f7d8
Revises: 4da7c72a83e8
Create Date: 2015-01-21 11:28:00.092553

"""

# revision identifiers, used by Alembic.
revision = '319c6602f7d8'
down_revision = '4da7c72a83e8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('additional_columns', sa.String(length=150), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'additional_columns')
    ### end Alembic commands ###
