"""empty message

Revision ID: 338942659374
Revises: 17ef0f7a67dd
Create Date: 2014-12-05 17:35:54.795960

"""

# revision identifiers, used by Alembic.
revision = '338942659374'
down_revision = '17ef0f7a67dd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'regexp', ['title'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'regexp')
    ### end Alembic commands ###
