"""empty message

Revision ID: 3423aeb220a3
Revises: bad36d30a45
Create Date: 2015-01-09 14:39:50.925137

"""

# revision identifiers, used by Alembic.
revision = '3423aeb220a3'
down_revision = 'bad36d30a45'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset', sa.Column('language', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset', 'language')
    ### end Alembic commands ###
