"""empty message

Revision ID: 35154b9730da
Revises: 3423aeb220a3
Create Date: 2015-01-09 15:55:35.469392

"""

# revision identifiers, used by Alembic.
revision = '35154b9730da'
down_revision = '3423aeb220a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topogram', sa.Column('networks', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topogram', 'networks')
    ### end Alembic commands ###
