"""empty message

Revision ID: 40cf67f2aa92
Revises: b90803851
Create Date: 2014-12-16 16:55:45.077007

"""

# revision identifiers, used by Alembic.
revision = '40cf67f2aa92'
down_revision = 'b90803851'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topogram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('es_index_name', sa.String(length=200), nullable=False),
    sa.Column('es_query', sa.String(length=150), nullable=False),
    sa.Column('data_mongo_id', sa.String(length=150), nullable=True),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('meme')
    op.create_foreign_key(None, 'dataset', 'topotype', ['topotype_id'], ['id'])
    op.create_foreign_key(None, 'regexp', 'topotype', ['citation_patterns_id'], ['id'])
    op.create_foreign_key(None, 'regexp', 'topotype', ['stop_patterns_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'regexp', type_='foreignkey')
    op.drop_constraint(None, 'regexp', type_='foreignkey')
    op.drop_constraint(None, 'dataset', type_='foreignkey')
    op.create_table('meme',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('description', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('es_index_name', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('es_query', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('data_mongo_id', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('records_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('dataset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], [u'dataset.id'], name=u'meme_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'meme_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('topogram')
    ### end Alembic commands ###
