"""empty message

Revision ID: 43042192957
Revises: 566521b93cf8
Create Date: 2014-12-05 11:10:51.417519

"""

# revision identifiers, used by Alembic.
revision = '43042192957'
down_revision = '566521b93cf8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regexp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('regexp', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'topogram_type', sa.Column('citation_pattern', sa.String(length=120), nullable=True))
    op.add_column(u'topogram_type', sa.Column('dest_column', sa.String(length=120), nullable=True))
    op.add_column(u'topogram_type', sa.Column('ignoreCitation', sa.String(length=120), nullable=True))
    op.add_column(u'topogram_type', sa.Column('languages', sa.String(length=120), nullable=True))
    op.add_column(u'topogram_type', sa.Column('source_column', sa.String(length=120), nullable=True))
    op.add_column(u'topogram_type', sa.Column('stop_patterns', sa.String(length=120), nullable=True))
    op.add_column(u'topogram_type', sa.Column('stopwords', sa.Text(), nullable=True))
    op.add_column(u'topogram_type', sa.Column('time_pattern', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'topogram_type', 'time_pattern')
    op.drop_column(u'topogram_type', 'stopwords')
    op.drop_column(u'topogram_type', 'stop_patterns')
    op.drop_column(u'topogram_type', 'source_column')
    op.drop_column(u'topogram_type', 'languages')
    op.drop_column(u'topogram_type', 'ignoreCitation')
    op.drop_column(u'topogram_type', 'dest_column')
    op.drop_column(u'topogram_type', 'citation_pattern')
    op.drop_table('regexp')
    ### end Alembic commands ###
