"""empty message

Revision ID: 4a881490645f
Revises: c05b609496b
Create Date: 2014-12-17 14:23:49.799238

"""

# revision identifiers, used by Alembic.
revision = '4a881490645f'
down_revision = 'c05b609496b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topogram', sa.Column('citations', sa.Text(), nullable=True))
    op.add_column('topogram', sa.Column('words', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topogram', 'words')
    op.drop_column('topogram', 'citations')
    ### end Alembic commands ###
