"""empty

Revision ID: 4aa5cfbe1499
Revises: 5a5f7f6f6ca
Create Date: 2014-11-29 11:48:32.297146

"""

# revision identifiers, used by Alembic.
revision = '4aa5cfbe1499'
down_revision = '5a5f7f6f6ca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
