"""create topogram_type

Revision ID: 4c6db136d964
Revises: 576b56952a32
Create Date: 2014-12-05 11:01:37.526207

"""

# revision identifiers, used by Alembic.
revision = '4c6db136d964'
down_revision = '576b56952a32'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topogram_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topogram_type')
    ### end Alembic commands ###
