"""Init

Revision ID: 4da7c72a83e8
Revises: None
Create Date: 2015-01-09 17:40:26.362518

"""

# revision identifiers, used by Alembic.
revision = '4da7c72a83e8'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regexps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('regexp', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('dataset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filepath', sa.String(length=120), nullable=True),
    sa.Column('index_name', sa.String(length=150), nullable=True),
    sa.Column('index_state', sa.String(length=150), nullable=False),
    sa.Column('source_column', sa.String(length=120), nullable=True),
    sa.Column('text_column', sa.String(length=120), nullable=True),
    sa.Column('time_column', sa.String(length=120), nullable=True),
    sa.Column('time_pattern', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topogram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('es_index_name', sa.String(length=200), nullable=False),
    sa.Column('es_query', sa.String(length=150), nullable=False),
    sa.Column('records_count', sa.Integer(), nullable=True),
    sa.Column('words_limit', sa.Integer(), nullable=True),
    sa.Column('citations_limit', sa.Integer(), nullable=True),
    sa.Column('stopwords', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=150), nullable=True),
    sa.Column('words', sa.Text(), nullable=True),
    sa.Column('citations', sa.Text(), nullable=True),
    sa.Column('networks', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topogram_regexps',
    sa.Column('topogram_id', sa.Integer(), nullable=True),
    sa.Column('regexp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['regexp_id'], ['regexps.id'], ),
    sa.ForeignKeyConstraint(['topogram_id'], ['topogram.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topogram_regexps')
    op.drop_table('topogram')
    op.drop_table('dataset')
    op.drop_table('user')
    op.drop_table('regexps')
    ### end Alembic commands ###
