"""empty message

Revision ID: 500722960d68
Revises: 4aa5cfbe1499
Create Date: 2014-11-29 11:55:26.797492

"""

# revision identifiers, used by Alembic.
revision = '500722960d68'
down_revision = '4aa5cfbe1499'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    ### end Alembic commands ###
