"""empty message

Revision ID: 501067fed1e3
Revises: 296b2056a300
Create Date: 2014-12-05 12:33:36.105620

"""

# revision identifiers, used by Alembic.
revision = '501067fed1e3'
down_revision = '296b2056a300'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topotype', sa.Column('text_column', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topotype', 'text_column')
    ### end Alembic commands ###
