"""empty message

Revision ID: 523d0809261
Revises: 2c6ae0707e99
Create Date: 2015-05-15 20:32:48.145911

"""

# revision identifiers, used by Alembic.
revision = '523d0809261'
down_revision = '2c6ae0707e99'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('topogram', 'records_count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topogram', sa.Column('records_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
