"""empty message

Revision ID: 54f2fab25c04
Revises: 338942659374
Create Date: 2014-12-05 17:55:06.153122

"""

# revision identifiers, used by Alembic.
revision = '54f2fab25c04'
down_revision = '338942659374'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
