"""empty message

Revision ID: 566521b93cf8
Revises: 4c6db136d964
Create Date: 2014-12-05 11:01:51.564015

"""

# revision identifiers, used by Alembic.
revision = '566521b93cf8'
down_revision = '4c6db136d964'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
