"""empty message

Revision ID: 568d2d75795c
Revises: 3863b4c659e3
Create Date: 2014-11-19 19:10:41.332777

"""

# revision identifiers, used by Alembic.
revision = '568d2d75795c'
down_revision = '3863b4c659e3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
