"""empty message

Revision ID: 576b56952a32
Revises: 2fc2f80eea15
Create Date: 2014-11-29 12:55:19.849575

"""

# revision identifiers, used by Alembic.
revision = '576b56952a32'
down_revision = '2fc2f80eea15'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=120), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    ### end Alembic commands ###
