"""empty message

Revision ID: 5a5f7f6f6ca
Revises: 2f02364e3076
Create Date: 2014-11-29 11:47:20.592830

"""

# revision identifiers, used by Alembic.
revision = '5a5f7f6f6ca'
down_revision = '2f02364e3076'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
