"""empty message

Revision ID: b2dd33a7d99
Revises: 19e0711f93bc
Create Date: 2015-05-15 20:03:29.035018

"""

# revision identifiers, used by Alembic.
revision = 'b2dd33a7d99'
down_revision = '19e0711f93bc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topogram_regexps')
    op.add_column('dataset', sa.Column('index_name', sa.String(length=150), nullable=True))
    op.add_column('dataset', sa.Column('index_state', sa.String(length=150), nullable=False))
    op.alter_column('dataset', 'title',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=120),
               nullable=True)
    op.drop_column('topogram', 'es_index_name')
    op.drop_column('topogram', 'es_query')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topogram', sa.Column('es_query', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=150), nullable=False))
    op.add_column('topogram', sa.Column('es_index_name', mysql.VARCHAR(collation=u'utf8_unicode_ci', length=200), nullable=False))
    op.alter_column('dataset', 'title',
               existing_type=mysql.VARCHAR(collation=u'utf8_unicode_ci', length=120),
               nullable=False)
    op.drop_column('dataset', 'index_state')
    op.drop_column('dataset', 'index_name')
    op.create_table('topogram_regexps',
    sa.Column('topogram_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('regexp_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['regexp_id'], [u'regexps.id'], name=u'topogram_regexps_ibfk_1'),
    sa.ForeignKeyConstraint(['topogram_id'], [u'topogram.id'], name=u'topogram_regexps_ibfk_2'),
    mysql_collate=u'utf8_unicode_ci',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
