"""empty message

Revision ID: b90803851
Revises: 16f9323ec957
Create Date: 2014-12-05 17:58:28.280025

"""

# revision identifiers, used by Alembic.
revision = 'b90803851'
down_revision = '16f9323ec957'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'topotype_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default='0')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dataset', 'topotype_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default='0')
    ### end Alembic commands ###
