"""empty message

Revision ID: c05b609496b
Revises: 2ec1e81b06f8
Create Date: 2014-12-16 18:20:45.353512

"""

# revision identifiers, used by Alembic.
revision = 'c05b609496b'
down_revision = '2ec1e81b06f8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
