"""empty message

Revision ID: eb14adbd6b4
Revises: 300f7090fbfb
Create Date: 2014-12-05 12:41:09.387933

"""

# revision identifiers, used by Alembic.
revision = 'eb14adbd6b4'
down_revision = '300f7090fbfb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topotype', sa.Column('ignore_citations', sa.String(length=120), nullable=True))
    op.add_column('topotype', sa.Column('timestamp_column', sa.String(length=120), nullable=True))
    op.drop_column('topotype', 'ignoreCitation')
    op.drop_column('topotype', 'time_column')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topotype', sa.Column('time_column', sa.VARCHAR(length=120), nullable=True))
    op.add_column('topotype', sa.Column('ignoreCitation', sa.VARCHAR(length=120), nullable=True))
    op.drop_column('topotype', 'timestamp_column')
    op.drop_column('topotype', 'ignore_citations')
    ### end Alembic commands ###
